name: Deploy and Manage Processes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
      commit:
        description: 'Commit to build'
        required: true
        default: 'latest'
      environment:
        description: 'Environment name'
        required: true
        default: '0'

jobs:
  deploy-and-manage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout specific commit
        if: ${{ github.event.inputs.commit != 'latest' }}
        run: git checkout ${{ github.event.inputs.commit }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Management Script
        run: |
          nohup node ./scripts/manage.js &

      - name: Install Localtunnel
        run: npm install -g localtunnel

      - name: Start Localtunnel
        run: |
          lt --port 4000 --subdomain my-custom-subdomain > localtunnel.log &
          sleep 5
          LOCAL_TUNNEL_URL=$(grep -o 'https://[a-z0-9\.]*.localtunnel.me' localtunnel.log | head -n 1)
          echo "Management app is exposed at: $LOCAL_TUNNEL_URL"
        id: get-localtunnel-url

      - name: Print Localtunnel URL
        run: |
          echo "Your management app is exposed at: ${{ steps.get-localtunnel-url.outputs.LOCAL_TUNNEL_URL }}"
